# Generated by Django 6.0.3 on 2026-03-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_veryfied',
            field=models.BooleanField(default=False),
        ),
    ]
