# Generated by Django 6.0.3 on 2026-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_register_is_veryfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='register',
            name='is_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
