# Generated by Django 6.0.3 on 2026-03-23 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_register_address_register_id_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_id_verified',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='register',
            name='pincode',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('is_id_verified', models.BooleanField(default=False)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
