# Generated by Django 6.0.4 on 2026-04-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userprofile_is_online_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Bio',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
