# Generated by Django 6.0.4 on 2026-04-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Bio',
            new_name='bio',
        ),
    ]
