# Generated by Django 6.0.4 on 2026-04-16 05:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
