# Generated by Django 6.0.3 on 2026-03-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_payment_status'),
        ('Services', '0003_providerservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('provider', 'payment_status', 'booking_date', 'booking_time')},
        ),
    ]
