# Generated by Django 6.0.3 on 2026-03-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_unique_together'),
        ('Services', '0003_providerservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('provider', 'booking_date', 'booking_time')},
        ),
    ]
