# Generated by Django 6.0.4 on 2026-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_providerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
